package provider

// radiusVendorPaloAlto holds the RADIUS attribute dictionary for PALO_ALTO.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorPaloAlto = VendorDictionaryInfo{
	Value:       "PALO_ALTO",
	Label:       "Palo Alto Networks",
	Description: "Palo Alto Networks RADIUS VSA (Vendor ID: 25461). Used with PAN-OS GlobalProtect VPN, Captive Portal, and management-plane authentication.",
	VendorID:    25461,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "PAN-OS-Admin-Role",
			AttributeID:    1,
			Label:       "Admin Role",
			Description: "PAN-OS admin role profile granted to the administrator",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"superreader", "deviceadmin", "custom-role"},
		},
		{
			Key:         "PAN-OS-Admin-Access-Domain",
			AttributeID:    2,
			Label:       "Admin Access Domain",
			Description: "Access domain restricting the admin to specific virtual systems or device groups",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"vsys1", "shared", "domain-emea"},
		},
		{
			Key:         "PAN-OS-Panorama-Admin-Role",
			AttributeID:    16,
			Label:       "Panorama Admin Role",
			Description: "Admin role granted on Panorama management server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"superuser", "panorama-admin", "read-only"},
		},
		{
			Key:         "PAN-OS-Panorama-Admin-Access-Domain",
			AttributeID:    17,
			Label:       "Panorama Admin Access Domain",
			Description: "Access domain on Panorama restricting device group / template scope",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"domain-apac", "domain-all"},
		},
		{
			Key:         "PAN-OS-User-Group",
			AttributeID:    3,
			Label:       "User Group",
			Description: "GlobalProtect / Captive Portal user group for policy matching",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"vpn-users", "contractors", "employees"},
		},
		{
			Key:         "PAN-OS-HIP-Report",
			AttributeID:    15,
			Label:       "HIP Report",
			Description: "Host Information Profile report data for endpoint compliance checking",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(253),
			Examples:    []string{"hip-basic-check"},
		},
		{
			Key:         "PAN-OS-Privilege-Level",
			AttributeID:    14,
			Label:       "Privilege Level",
			Description: "Numeric privilege level for RADIUS-based device management (1–15)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"15", "5"},
		},
	},
}