package provider

// radiusVendorUbiquiti holds the RADIUS attribute dictionary for UBIQUITI.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorUbiquiti = VendorDictionaryInfo{
	Value:       "UBIQUITI",
	Label:       "Ubiquiti Networks (UniFi)",
	Description: "Ubiquiti Networks RADIUS VSA (Vendor ID: 41112). UniFi primarily uses standard RADIUS attributes; these VSAs cover UniFi-specific extensions.",
	VendorID:    41112,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Ubiquiti-User-Group",
			AttributeID:    2,
			Label:       "User Group",
			Description: "UniFi user-group name used for bandwidth policy assignment",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"Default", "Staff", "Guest"},
		},
		{
			Key:         "Ubiquiti-WLAN-ID",
			AttributeID:    1,
			Label:       "WLAN ID",
			Description: "UniFi WLAN identifier to which the client is mapped",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			Examples:    []string{"corp-ssid", "iot-ssid"},
		},
		{
			Key:         "Ubiquiti-No-DHCP-Gateway",
			AttributeID:    8,
			Label:       "No DHCP Gateway",
			Description: "Suppress the default gateway in DHCP response to the client (1 = suppress)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(1),
			Examples:    []string{"1"},
		},
		{
			Key:         "Ubiquiti-Wireless-Rate-Limit-Up",
			AttributeID:    5,
			Label:       "Wireless Rate Limit Up",
			Description: "Maximum upstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200"},
		},
		{
			Key:         "Ubiquiti-Wireless-Rate-Limit-Down",
			AttributeID:    4,
			Label:       "Wireless Rate Limit Down",
			Description: "Maximum downstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480", "102400"},
		},
		{
			Key:         "Ubiquiti-Wireless-Rate-Limit-Up-Burst",
			AttributeID:    7,
			Label:       "Wireless Rate Limit Up Burst",
			Description: "Burst upstream bandwidth allowed above the rate limit, in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480"},
		},
		{
			Key:         "Ubiquiti-Wireless-Rate-Limit-Down-Burst",
			AttributeID:    6,
			Label:       "Wireless Rate Limit Down Burst",
			Description: "Burst downstream bandwidth allowed above the rate limit, in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"40960"},
		},
		{
			Key:         "Ubiquiti-Site-Name",
			AttributeID:    3,
			Label:       "Site Name",
			Description: "UniFi site name the client belongs to (multi-site deployments)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(64),
			Examples:    []string{"default", "branch-office"},
		},
	},
}