package provider

// radiusVendorCisco holds the RADIUS attribute dictionary for CISCO.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorCisco = VendorDictionaryInfo{
	Value:       "CISCO",
	Label:       "Cisco",
	Description: "Cisco specific RADIUS attributes (Vendor ID: 9).",
	VendorID:    9,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Cisco-AVPair",
			AttributeID:    1,
			Label:       "Cisco AVPair",
			Description: "Arbitrary AV-Pairs used for advanced Cisco configs. Format: attribute=value",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryVendorSpecific,
			Required:    false,
			Pattern:     `^[a-zA-Z0-9_-]+=.+$`,
			Examples:    []string{"client-mac-address=00:11:22:33:44:55", "ip:inacl#1=permit ip any any", "tunnel-type=1"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Cisco-NAS-Port",
			AttributeID:    2,
			Label:       "Cisco NAS Port",
			Description: "Cisco specific NAS port format",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Multilink-ID",
			Label:       "Multilink ID",
			Description: "Multilink bundle ID",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Cisco-Multilink-Maxlinks",
			Label:       "Multilink Max Links",
			Description: "Maximum number of links in multilink bundle",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(255),
			Examples:    []string{"2", "4", "8"},
		},
		{
			Key:         "Cisco-Password-Expiry",
			Label:       "Password Expiry",
			Description: "Days until password expires",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"30", "60", "90"},
		},
		{
			Key:         "Cisco-Service-Info",
			Label:       "Service Info",
			Description: "Service information for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"service1", "premium"},
		},
		{
			Key:         "Cisco-Command-Code",
			Label:       "Command Code",
			Description: "Command code to execute",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Cisco-Script-Path",
			Label:       "Script Path",
			Description: "Path to script to execute",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Cisco-Disconnect-Cause",
			AttributeID:    86,
			Label:       "Disconnect Cause",
			Description: "Reason for disconnection",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Data-Rate",
			Label:       "Data Rate",
			Description: "Data rate in bps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10000000", "100000000"},
		},
		{
			Key:         "Cisco-Presence",
			Label:       "Presence",
			Description: "Presence attribute",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Call-Filter",
			AttributeID:    36,
			Label:       "Call Filter",
			Description: "Call filter to apply",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			Required:    false,
		},
		{
			Key:         "Cisco-Idlepat",
			Label:       "Idle Pattern",
			Description: "Idle pattern detection",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Tunnel-Private-Group-ID",
			Label:       "Tunnel Private Group ID",
			Description: "Private group ID for tunneling",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Examples:    []string{"100", "VLAN100"},
		},
		{
			Key:         "Cisco-Tunnel-Preference",
			Label:       "Tunnel Preference",
			Description: "Tunnel preference value",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Cisco-IP-Direct",
			AttributeID:    100,
			Label:       "IP Direct",
			Description: "Enable IP direct routing",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryRouting,
			Required:    false,
		},
		{
			Key:         "Cisco-PPP-VJ-Slot-Comp",
			AttributeID:    101,
			Label:       "PPP VJ Slot Compression",
			Description: "Enable Van Jacobson TCP/IP header compression",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Cisco-PPP-Async-Map",
			Label:       "PPP Async Map",
			Description: "PPP async control character map",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(4294967295),
		},
		{
			Key:         "Cisco-Packet-Type",
			Label:       "Packet Type",
			Description: "Packet type identifier",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Num-In-Sessions",
			Label:       "Number of In Sessions",
			Description: "Number of incoming sessions",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Cisco-Proxy-Acl",
			Label:       "Proxy ACL",
			Description: "Proxy access control list",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			Required:    false,
		},
		{
			Key:         "Cisco-Authen-Method",
			Label:       "Authentication Method",
			Description: "Authentication method used",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Not Set"},
				{Value: "1", Label: "None"},
				{Value: "2", Label: "KRB5"},
				{Value: "3", Label: "Line"},
				{Value: "4", Label: "Enable"},
				{Value: "5", Label: "Local"},
				{Value: "6", Label: "Tacacs+"},
				{Value: "7", Label: "RADIUS"},
			},
		},
		{
			Key:         "Cisco-Authen-Type",
			Label:       "Authentication Type",
			Description: "Type of authentication",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Not Set"},
				{Value: "1", Label: "ASCII"},
				{Value: "2", Label: "PAP"},
				{Value: "3", Label: "CHAP"},
				{Value: "4", Label: "ARAP"},
				{Value: "5", Label: "MS-CHAP"},
				{Value: "6", Label: "MS-CHAPv2"},
				{Value: "7", Label: "EAP"},
			},
		},
		{
			Key:         "Cisco-Service-Type",
			Label:       "Service Type",
			Description: "Service type for authorization",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "Shell"},
				{Value: "2", Label: "TTY"},
				{Value: "3", Label: "Network"},
				{Value: "4", Label: "Fwd"},
				{Value: "5", Label: "Outbound"},
				{Value: "6", Label: "System"},
			},
		},
		{
			Key:         "Cisco-User-Privilege-Level",
			Label:       "User Privilege Level",
			Description: "Cisco privilege level (0-15)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"1", "15", "0"},
		},
		{
			Key:         "Cisco-IP-Pool-Definition",
			Label:       "IP Pool Definition",
			Description: "IP pool name to use",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"POOL1", "default-pool"},
		},
		{
			Key:         "Cisco-Assign-IP-Pool",
			Label:       "Assign IP Pool",
			Description: "IP pool assignment method",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Local Pool"},
				{Value: "1", Label: "DHCP Proxy"},
			},
		},
		{
			Key:         "Cisco-Link-Compression",
			Label:       "Link Compression",
			Description: "Enable link compression",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "Stac"},
				{Value: "2", Label: "MPPC"},
				{Value: "3", Label: "Stac-LZS"},
			},
		},
		{
			Key:         "Cisco-Target-Utility",
			Label:       "Target Utility",
			Description: "Target utility for compression",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(255),
		},
		{
			Key:         "Cisco-Maximum-Channels",
			Label:       "Maximum Channels",
			Description: "Maximum number of channels",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(1),
			Examples:    []string{"1", "2", "4"},
		},
		{
			Key:         "Cisco-Encryption-Type",
			Label:       "Encryption Type",
			Description: "Encryption type to use",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "MD5"},
				{Value: "2", Label: "DES"},
			},
		},
		{
			Key:         "Cisco-Event",
			Label:       "Event",
			Description: "Event type",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Cisco-Account-Info",
			Label:       "Account Info",
			Description: "Accounting information",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAccounting,
			Required:    false,
		},
		{
			Key:         "Cisco-Progress",
			Label:       "Progress",
			Description: "Progress indicator",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
	},
}