package provider

// radiusVendorJuniper holds the RADIUS attribute dictionary for JUNIPER.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorJuniper = VendorDictionaryInfo{
	Value:       "JUNIPER",
	Label:       "Juniper Networks",
	Description: "Juniper Networks RADIUS VSA (Vendor ID: 2636). Used for JunOS device management and subscriber session policy (JunosE/BNG).",
	VendorID:    2636,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Juniper-Local-User-Name",
			AttributeID:    1,
			Label:       "Local User Name",
			Description: "Local account on the JunOS device to clone access rights from",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(64),
			Examples:    []string{"operator", "read-only"},
		},
		{
			Key:         "Juniper-Allow-Commands",
			AttributeID:    2,
			Label:       "Allow Commands",
			Description: "Regular expression of CLI commands the user is permitted to run",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"show .*", "show (interfaces|route).*"},
		},
		{
			Key:         "Juniper-Deny-Commands",
			AttributeID:    3,
			Label:       "Deny Commands",
			Description: "Regular expression of CLI commands the user is forbidden from running",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"(set|delete|rollback) .*"},
		},
		{
			Key:         "Juniper-Allow-Configuration",
			AttributeID:    4,
			Label:       "Allow Configuration",
			Description: "Regular expression of configuration hierarchy paths the user may modify",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"interfaces .*", "protocols ospf.*"},
		},
		{
			Key:         "Juniper-Deny-Configuration",
			AttributeID:    5,
			Label:       "Deny Configuration",
			Description: "Regular expression of configuration hierarchy paths the user is denied",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"system security.*", "system login.*"},
		},
		{
			Key:         "Juniper-User-Permissions",
			AttributeID:    10,
			Label:       "User Permissions",
			Description: "Space-separated list of JunOS permission flags (e.g. view, configure, admin)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"view", "view configure", "all"},
		},
		{
			Key:         "Juniper-Primary-Dns",
			AttributeID:    15,
			Label:       "Primary DNS",
			Description: "Primary DNS server to assign to the subscriber session",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "Juniper-Secondary-Dns",
			AttributeID:    16,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server to assign to the subscriber session",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "Juniper-Primary-Wins",
			AttributeID:    17,
			Label:       "Primary WINS",
			Description: "Primary WINS server for the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"192.168.1.10"},
		},
		{
			Key:         "Juniper-Secondary-Wins",
			AttributeID:    18,
			Label:       "Secondary WINS",
			Description: "Secondary WINS server for the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"192.168.1.11"},
		},
		{
			Key:         "Juniper-Interface-Group",
			AttributeID:    6,
			Label:       "Interface Group",
			Description: "Logical interface (IFL) group name for the subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"ifl-group-gold", "grp-default"},
		},
		{
			Key:         "Juniper-Cos-Traffic-Control-Id",
			AttributeID:    26,
			Label:       "CoS Traffic Control ID",
			Description: "Class-of-Service traffic control profile name to apply to the session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			Examples:    []string{"tc-gold", "tc-10m"},
		},
		{
			Key:         "Juniper-Policy-Option-Name",
			AttributeID:    25,
			Label:       "Policy Option Name",
			Description: "Routing policy option to apply to the subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"subscriber-opt-1"},
		},
		{
			Key:         "Juniper-Session-Volume-Quota",
			AttributeID:    42,
			Label:       "Session Volume Quota",
			Description: "Total bidirectional volume quota for the session in bytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10737418240", "0"},
		},
	},
}