package provider

// radiusVendorA10Networks holds the RADIUS attribute dictionary for A10_NETWORKS.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorA10Networks = VendorDictionaryInfo{
	Value:       "A10_NETWORKS",
	Label:       "A10 Networks (CGN/CGNAT)",
	Description: "A10 Networks RADIUS VSA (Vendor ID: 22610). Used with A10 Thunder CGN appliances for large-scale NAT subscriber policy control.",
	VendorID:    22610,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "A10-Bandwidth-Rate-Limit-Down",
			AttributeID:    1,
			Label:       "Bandwidth Rate Limit Down",
			Description: "Maximum downstream bandwidth rate for the subscriber in bps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"100000000", "1000000000"},
		},
		{
			Key:         "A10-Bandwidth-Rate-Limit-Up",
			AttributeID:    2,
			Label:       "Bandwidth Rate Limit Up",
			Description: "Maximum upstream bandwidth rate for the subscriber in bps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10000000", "100000000"},
		},
		{
			Key:         "A10-Count-Limit",
			AttributeID:    4,
			Label:       "Session Count Limit",
			Description: "Maximum number of concurrent NAT sessions allowed for the subscriber",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"1000", "4096", "65535"},
		},
		{
			Key:         "A10-Session-Volume-Quota",
			AttributeID:    7,
			Label:       "Session Volume Quota",
			Description: "Total data volume quota for the subscriber session in bytes",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"107374182400", "0"},
		},
		{
			Key:         "A10-Nat-Pool",
			AttributeID:    3,
			Label:       "NAT Pool",
			Description: "Public IP address pool name from which CGNAT addresses are allocated",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"nat-pool-1", "cgnat-outside-pool"},
		},
		{
			Key:         "A10-Fixed-NAT-Port-Range-Start",
			AttributeID:    8,
			Label:       "Fixed NAT Port Range Start",
			Description: "Start of the fixed port block assigned to this subscriber for deterministic CGNAT",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(1024),
			MaxValue:    float64Ptr(65535),
			Examples:    []string{"1024", "10000"},
		},
		{
			Key:         "A10-Fixed-NAT-Port-Range-End",
			AttributeID:    9,
			Label:       "Fixed NAT Port Range End",
			Description: "End of the fixed port block assigned to this subscriber for deterministic CGNAT",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(1024),
			MaxValue:    float64Ptr(65535),
			Examples:    []string{"2047", "10511"},
		},
		{
			Key:         "A10-Inside-VRF",
			AttributeID:    5,
			Label:       "Inside VRF",
			Description: "VRF / routing table name for the subscriber's inside (private) interface",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"inside-vrf", "cgnat-inside"},
		},
		{
			Key:         "A10-Outside-VRF",
			AttributeID:    6,
			Label:       "Outside VRF",
			Description: "VRF / routing table name for the CGNAT outside (public) interface",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"outside-vrf", "cgnat-outside"},
		},
	},
}