package provider

// radiusVendorFortinet holds the RADIUS attribute dictionary for FORTINET.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorFortinet = VendorDictionaryInfo{
	Value:       "FORTINET",
	Label:       "Fortinet",
	Description: "Fortinet RADIUS VSA (Vendor ID: 12356). Used with FortiGate firewalls, FortiSwitch, and FortiAuthenticator.",
	VendorID:    12356,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Fortinet-Group-Name",
			AttributeID:    1,
			Label:       "Group Name",
			Description: "User group membership on the FortiGate; controls firewall policy matching",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(255),
			Examples:    []string{"VPN-Users", "Admin-Group", "Guest-WiFi"},
		},
		{
			Key:         "Fortinet-Client-IP-Address",
			AttributeID:    2,
			Label:       "Client IP Address",
			Description: "Static IP address to assign to the VPN client tunnel interface",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"10.0.0.100", "172.16.0.50"},
		},
		{
			Key:         "Fortinet-Vdom-Name",
			AttributeID:    3,
			Label:       "VDOM Name",
			Description: "Virtual domain (VDOM) on the FortiGate to which the user is scoped",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"root", "vdom-branch", "vdom-dmz"},
		},
		{
			Key:         "Fortinet-Vlan-Interface",
			AttributeID:    7,
			Label:       "VLAN Interface",
			Description: "VLAN interface name on FortiSwitch to assign to the authenticated port",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(64),
			Examples:    []string{"vlan100", "vlan-staff", "vlan-iot"},
		},
		{
			Key:         "Fortinet-Access-Profile",
			AttributeID:    6,
			Label:       "Access Profile",
			Description: "Administrative access profile granting device management permissions",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"super_admin", "prof_admin", "read_only", "no_access"},
		},
		{
			Key:         "Fortinet-User-Profile",
			AttributeID:    8,
			Label:       "User Profile",
			Description: "FSSO user profile used for endpoint identity-based policy matching",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"profile-corp", "profile-guest"},
		},
		{
			Key:         "Fortinet-Webfilter-Profile",
			AttributeID:    26,
			Label:       "Web Filter Profile",
			Description: "Web filtering profile to apply to the user's traffic",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(64),
			Examples:    []string{"default", "strict", "custom-filter", "monitor"},
		},
		{
			Key:         "Fortinet-Virus-Profile",
			AttributeID:    25,
			Label:       "Antivirus Profile",
			Description: "Antivirus profile to apply inline to the user's sessions",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(64),
			Examples:    []string{"default", "high-security"},
		},
		{
			Key:         "Fortinet-Interface",
			AttributeID:    5,
			Label:       "Interface",
			Description: "Network interface on the FortiGate associated with this user session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(64),
			Examples:    []string{"port1", "internal", "wan1"},
		},
		{
			Key:         "Fortinet-Privilege-Level",
			AttributeID:    9,
			Label:       "Privilege Level",
			Description: "CLI privilege level on the FortiGate (15 = super_admin, 0 = no access)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"15", "7", "1", "0"},
		},
		{
			Key:         "Fortinet-Disallow-WAN",
			Label:       "Disallow WAN",
			Description: "Prevent the SSL-VPN user from splitting traffic to the WAN (1 = disallow)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(1),
			Examples:    []string{"1"},
		},
	},
}