package provider

// radiusVendorCasaSystems holds the RADIUS attribute dictionary for CASA_SYSTEMS.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorCasaSystems = VendorDictionaryInfo{
	Value:       "CASA_SYSTEMS",
	Label:       "Casa Systems",
	Description: "Casa Systems RADIUS VSA (Vendor ID: 20858). Used with Casa CMTS and vCMTS platforms for cable subscriber management and CGNAT policy control.",
	VendorID:    20858,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Casa-Subscriber-Profile",
			AttributeID:    2,
			Label:       "Subscriber Profile",
			Description: "Service profile name for the cable subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"prof-100m", "prof-1g-docsis31"},
		},
		{
			Key:         "Casa-Rate-Limit-Up",
			AttributeID:    4,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream channel rate for the CM subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200"},
		},
		{
			Key:         "Casa-Rate-Limit-Down",
			AttributeID:    3,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream channel rate for the CM subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"102400", "1024000"},
		},
		{
			Key:         "Casa-NAT-Policy",
			AttributeID:    8,
			Label:       "NAT Policy",
			Description: "CGNAT NAT44 policy name applied to the cable subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"cgnat-pol-default", "nat-pol-strict"},
		},
		{
			Key:         "Casa-IP-Pool",
			AttributeID:    5,
			Label:       "IP Pool",
			Description: "IP address pool from which the subscriber's CPE address is allocated",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"pool-cable-residential", "pool-cgnat-public"},
		},
		{
			Key:         "Casa-Primary-DNS",
			AttributeID:    6,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the cable modem subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "Casa-Secondary-DNS",
			AttributeID:    7,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the cable modem subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "Casa-Subscriber-ID",
			AttributeID:    1,
			Label:       "Subscriber ID",
			Description: "Unique subscriber/account identifier for billing system correlation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(64),
			Examples:    []string{"acct-00001234"},
		},
	},
}