package provider

// radiusVendorHuawei holds the RADIUS attribute dictionary for HUAWEI.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorHuawei = VendorDictionaryInfo{
	Value:       "HUAWEI",
	Label:       "Huawei",
	Description: "Huawei RADIUS VSA (Vendor ID: 2011). Used with Huawei BNG (SmartAX/ME60), enterprise routers, and switches.",
	VendorID:    2011,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "HW-Input-Average-Rate",
			AttributeID:    1,
			Label:       "Input Average Rate (CIR)",
			Description: "Committed information rate for ingress traffic in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200", "102400"},
		},
		{
			Key:         "HW-Input-Peak-Rate",
			AttributeID:    2,
			Label:       "Input Peak Rate (PIR)",
			Description: "Peak information rate for ingress traffic in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480", "102400"},
		},
		{
			Key:         "HW-Output-Average-Rate",
			AttributeID:    4,
			Label:       "Output Average Rate (CIR)",
			Description: "Committed information rate for egress traffic in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200", "102400"},
		},
		{
			Key:         "HW-Output-Peak-Rate",
			AttributeID:    5,
			Label:       "Output Peak Rate (PIR)",
			Description: "Peak information rate for egress traffic in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480", "102400"},
		},
		{
			Key:         "HW-User-Group",
			AttributeID:    50,
			Label:       "User Group",
			Description: "User group name used to apply QoS and policy templates",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"gold", "silver", "trial", "default"},
		},
		{
			Key:         "HW-Command",
			AttributeID:    20,
			Label:       "Command",
			Description: "CLI command the user is authorized to execute (device management)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"display .*", "display version"},
		},
		{
			Key:         "HW-Primary-Dns",
			AttributeID:    135,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the subscriber via PPP/DHCP",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "HW-Secondary-Dns",
			AttributeID:    136,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the subscriber via PPP/DHCP",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "HW-Policy-Name",
			AttributeID:    44,
			Label:       "Policy Name",
			Description: "QoS policy profile name to apply to the subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"pol-gold", "pol-default"},
		},
		{
			Key:         "HW-Subscribe-QoS",
			AttributeID:    46,
			Label:       "Subscribe QoS",
			Description: "Subscribed QoS profile that defines the service template",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"qos-profile-10m", "qos-profile-100m"},
		},
		{
			Key:         "HW-ANCP-Profile",
			AttributeID:    171,
			Label:       "ANCP Profile",
			Description: "ANCP (Access Node Control Protocol) profile for DSL line rate signalling",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"ancp-default", "ancp-vdsl2"},
		},
		{
			Key:         "HW-Domain-Name",
			AttributeID:    53,
			Label:       "Domain Name",
			Description: "ISP domain the subscriber session is bound to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(64),
			Examples:    []string{"isp.example.com", "residential"},
		},
		{
			Key:         "HW-Framed-Pool",
			AttributeID:    25,
			Label:       "Framed Pool",
			Description: "IP address pool name from which to allocate the subscriber's IP",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"pool-residential", "pool-business"},
		},
	},
}
