package provider

// radiusVendorZte holds the RADIUS attribute dictionary for ZTE.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorZte = VendorDictionaryInfo{
	Value:       "ZTE",
	Label:       "ZTE ZXBNG",
	Description: "ZTE RADIUS VSA (Vendor ID: 3902). Widely used in Asian and emerging-market ISPs with ZXBNG/ZXAN platforms for PPPoE, IPoE, and CGNAT subscriber management.",
	VendorID:    3902,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "ZTE-User-Profile",
			AttributeID:    4,
			Label:       "User Profile",
			Description: "Subscriber service profile defining QoS, ACL, and feature settings",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"prof-100m-residential", "prof-1g-business"},
		},
		{
			Key:         "ZTE-Rate-Limit-Up",
			AttributeID:    2,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream (subscriber → network) rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "102400"},
		},
		{
			Key:         "ZTE-Rate-Limit-Down",
			AttributeID:    1,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream (network → subscriber) rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"51200", "1024000"},
		},
		{
			Key:         "ZTE-Primary-DNS",
			AttributeID:    6,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the subscriber via PPP or DHCP",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "114.114.114.114"},
		},
		{
			Key:         "ZTE-Secondary-DNS",
			AttributeID:    7,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "114.114.115.115"},
		},
		{
			Key:         "ZTE-IP-Pool",
			AttributeID:    5,
			Label:       "IP Pool",
			Description: "IP address pool name from which to allocate the subscriber's address",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"pool-residential", "pool-cgnat"},
		},
		{
			Key:         "ZTE-NAT-Policy",
			AttributeID:    9,
			Label:       "NAT Policy",
			Description: "CGNAT NAT44 policy name applied to the subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"nat-pol-default", "cgnat-pol-strict"},
		},
		{
			Key:         "ZTE-VRF-Name",
			AttributeID:    8,
			Label:       "VRF Name",
			Description: "VRF / routing instance the subscriber session is placed in",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"vrf-residential", "vrf-business"},
		},
		{
			Key:         "ZTE-Acct-Input-Octets",
			AttributeID:    10,
			Label:       "Acct Input Octets (64-bit)",
			Description: "64-bit input octet counter extension for high-speed subscribers",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "ZTE-Acct-Output-Octets",
			AttributeID:    11,
			Label:       "Acct Output Octets (64-bit)",
			Description: "64-bit output octet counter extension for high-speed subscribers",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "ZTE-Subscriber-ID",
			AttributeID:    3,
			Label:       "Subscriber ID",
			Description: "Unique subscriber identifier for billing system correlation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(64),
			Examples:    []string{"sub-0001234", "contract-9876"},
		},
	},
}
