package provider

// radiusVendorStarent holds the RADIUS attribute dictionary for STARENT.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorStarent = VendorDictionaryInfo{
	Value:       "STARENT",
	Label:       "Starent / Cisco ASR 5000 (StarOS)",
	Description: "Starent Networks (now Cisco ASR 5000 StarOS) RADIUS VSA (Vendor ID: 8164). Used in mobile networks for P-GW, GGSN, and HA functions including large-scale CGNAT.",
	VendorID:    8164,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "SN-Volume-Quota-Giga",
			AttributeID:    8,
			Label:       "Volume Quota (Gigabytes)",
			Description: "Total data volume quota for the subscriber in gigabytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"100", "500", "0"},
		},
		{
			Key:         "SN-VPN-ID",
			AttributeID:    1,
			Label:       "VPN ID",
			Description: "VRF / APN VPN identifier for the subscriber's packet data session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"internet.mnc001.mcc001.gprs", "ims"},
		},
		{
			Key:         "SN-Subscriber-Profile",
			AttributeID:    7,
			Label:       "Subscriber Profile",
			Description: "Subscriber profile name defining QoS, PCC rules, and feature sets",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"default-bearer-profile", "ims-profile"},
		},
		{
			Key:         "SN-Rate-Limit-Up",
			AttributeID:    6,
			Label:       "Rate Limit Up",
			Description: "Maximum uplink data rate for the subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"51200", "204800"},
		},
		{
			Key:         "SN-Rate-Limit-Down",
			AttributeID:    5,
			Label:       "Rate Limit Down",
			Description: "Maximum downlink data rate for the subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"102400", "1024000"},
		},
		{
			Key:         "SN-Firewall-Policy",
			AttributeID:    2,
			Label:       "Firewall Policy",
			Description: "Stateful firewall policy name applied to the subscriber's data session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(64),
			Examples:    []string{"fw-pol-default", "fw-pol-ims"},
		},
		{
			Key:         "SN-NAT-Policy",
			AttributeID:    4,
			Label:       "NAT Policy",
			Description: "CGNAT NAT44 / NAT64 policy applied to the subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"nat-pol-lsn", "nat-pol-464xlat"},
		},
		{
			Key:         "SN-NAT-Pool-Name",
			AttributeID:    3,
			Label:       "NAT Pool Name",
			Description: "Public IP address pool for CGNAT outside address allocation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"cgnat-pool-1", "nat-outside"},
		},
		{
			Key:         "SN-Max-Concurrent-Sessions",
			AttributeID:    10,
			Label:       "Max Concurrent Sessions",
			Description: "Maximum number of concurrent NAT/data sessions for the subscriber",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"1024", "4096", "0"},
		},
		{
			Key:         "SN-CF-Policy-ID",
			AttributeID:    9,
			Label:       "Content Filtering Policy ID",
			Description: "Content filtering policy identifier for subscriber traffic inspection",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryFiltering,
			MinValue:    float64Ptr(0),
			Examples:    []string{"1", "5", "10"},
		},
	},
}
