package provider

// radiusVendorStandard holds the RADIUS attribute dictionary for STANDARD.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorStandard = VendorDictionaryInfo{
	Value:       "STANDARD",
	Label:       "Standard RADIUS",
	Description: "Standard RADIUS parameters defined by RFCs (RFC 2865, RFC 2866, RFC 2869).",
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "User-Name",
			AttributeID: 1,
			Label:       "User Name",
			Description: "The name of the user being authenticated",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    true,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(253),
			Examples:    []string{"john.doe@example.com", "user123"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "User-Password",
			AttributeID: 2,
			Label:       "User Password",
			Description: "The password of the user (encrypted)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(128),
		},
		{
			Key:         "CHAP-Password",
			AttributeID: 3,
			Label:       "CHAP Password",
			Description: "The CHAP password for CHAP authentication",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(17),
			MaxLength:   intPtr(17),
		},
		{
			Key:         "NAS-IP-Address",
			AttributeID: 4,
			Label:       "NAS IP Address",
			Description: "The IP address of the Network Access Server",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"192.168.1.1", "10.0.0.1"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "NAS-Port",
			AttributeID: 5,
			Label:       "NAS Port",
			Description: "The physical port number of the NAS",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(65535),
			Examples:    []string{"0", "5000"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Service-Type",
			AttributeID: 6,
			Label:       "Service Type",
			Description: "The type of service the user is requesting",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "Login"},
				{Value: "2", Label: "Framed"},
				{Value: "3", Label: "Callback Login"},
				{Value: "4", Label: "Callback Framed"},
				{Value: "5", Label: "Outbound"},
				{Value: "6", Label: "Administrative"},
				{Value: "7", Label: "NAS Prompt"},
				{Value: "8", Label: "Authenticate Only"},
				{Value: "9", Label: "Callback NAS Prompt"},
				{Value: "10", Label: "Call Check"},
				{Value: "11", Label: "Callback Administrative"},
				{Value: "12", Label: "Framed-Management"},
			},
			CoAApplicable:  true,
		},
		{
			Key:         "Framed-Protocol",
			AttributeID: 7,
			Label:       "Framed Protocol",
			Description: "The framing protocol to be used",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "PPP"},
				{Value: "2", Label: "SLIP"},
				{Value: "3", Label: "ARAP"},
				{Value: "4", Label: "Gandalf SLIP"},
				{Value: "5", Label: "Xylogics IPX SLIP"},
				{Value: "6", Label: "X.75 Synchronous"},
			},
			CoAApplicable:  true,
		},
		{
			Key:         "Framed-IP-Address",
			AttributeID: 8,
			Label:       "Framed IP Address",
			Description: "Address to be configured for the user (255.255.255.254 indicates NAS should select)",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"192.168.1.100", "10.0.0.50"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Framed-IP-Netmask",
			AttributeID: 9,
			Label:       "Framed IP Netmask",
			Description: "Netmask to be configured for the user",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"255.255.255.0", "255.255.0.0"},
			CoAApplicable:  true,
		},
		{
			Key:         "Framed-Routing",
			AttributeID: 10,
			Label:       "Framed Routing",
			Description: "Routing method for the user",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryRouting,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "Send routing packets"},
				{Value: "2", Label: "Listen for routing packets"},
				{Value: "3", Label: "Send and Listen"},
			},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Filter-Id",
			AttributeID: 11,
			Label:       "Filter ID",
			Description: "Filter list to be applied to the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			Required:    false,
			Examples:    []string{"filter.in", "filter.out"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Framed-MTU",
			AttributeID: 12,
			Label:       "Framed MTU",
			Description: "Maximum Transmission Unit for the user",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(64),
			MaxValue:    float64Ptr(65535),
			Examples:    []string{"1500", "1492"},
			CoAApplicable:  true,
		},
		{
			Key:         "Framed-Compression",
			AttributeID: 13,
			Label:       "Framed Compression",
			Description: "Compression protocol to be used",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "VJ TCP/IP header compression"},
				{Value: "2", Label: "IPX header compression"},
				{Value: "3", Label: "Stac-LZS compression"},
			},
			CoAApplicable:  true,
		},
		{
			Key:         "Login-IP-Host",
			AttributeID: 14,
			Label:       "Login IP Host",
			Description: "System with which to connect the user",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"192.168.1.10"},
		},
		{
			Key:         "Login-Service",
			AttributeID: 15,
			Label:       "Login Service",
			Description: "Service to use for connecting the user",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Telnet"},
				{Value: "1", Label: "Rlogin"},
				{Value: "2", Label: "TCP-Clear"},
				{Value: "3", Label: "PortMaster"},
				{Value: "4", Label: "LAT"},
				{Value: "5", Label: "X25-PAD"},
				{Value: "6", Label: "X25-T3POS"},
				{Value: "7", Label: "Unassigned"},
				{Value: "8", Label: "TCP"},
			},
		},
		{
			Key:         "Login-TCP-Port",
			AttributeID: 16,
			Label:       "Login TCP Port",
			Description: "TCP port to which to connect the user",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(65535),
			Examples:    []string{"23", "22", "80"},
		},
		{
			Key:         "Reply-Message",
			AttributeID: 18,
			Label:       "Reply Message",
			Description: "Message to be displayed to the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MaxLength:   intPtr(253),
			Examples:    []string{"Welcome to the network!", "Access granted"},
			MultiValue:     true,
		},
		{
			Key:         "Callback-Number",
			AttributeID: 19,
			Label:       "Callback Number",
			Description: "Phone number to call back",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"1234567890"},
		},
		{
			Key:         "Callback-Id",
			AttributeID: 20,
			Label:       "Callback ID",
			Description: "Callback identifier",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Framed-Route",
			AttributeID: 22,
			Label:       "Framed Route",
			Description: "Routing information to be configured for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryRouting,
			Required:    false,
			Pattern:     `^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/\d{1,2}(\s+[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(\s+\d+)?)?$`,
			Examples:    []string{"192.168.1.0/24", "10.0.0.0/8 192.168.1.1 1"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Framed-IPX-Network",
			AttributeID: 23,
			Label:       "Framed IPX Network",
			Description: "IPX network number to be configured",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryRouting,
			Required:    false,
			Pattern:     `^[0-9A-Fa-f]{1,8}$`,
			Examples:    []string{"ABCDEF12", "12345678"},
		},
		{
			Key:         "State",
			AttributeID: 24,
			Label:       "State",
			Description: "State information to be maintained between client and server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Class",
			AttributeID: 25,
			Label:       "Class",
			Description: "Class information to be maintained between client and server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MultiValue:     true,
		},
		{
			Key:         "Vendor-Specific",
			AttributeID: 26,
			Label:       "Vendor Specific",
			Description: "Vendor-specific attributes",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryVendorSpecific,
			Required:    false,
			CoAApplicable:  true,
		},
		{
			Key:         "Session-Timeout",
			AttributeID: 27,
			Label:       "Session Timeout",
			Description: "Maximum number of seconds of service to be provided",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"3600", "7200"},
			CoAApplicable:  true,
		},
		{
			Key:         "Idle-Timeout",
			AttributeID: 28,
			Label:       "Idle Timeout",
			Description: "Maximum number of consecutive seconds of idle connection allowed",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"300", "600"},
			CoAApplicable:  true,
		},
		{
			Key:         "Termination-Action",
			AttributeID: 29,
			Label:       "Termination Action",
			Description: "Action to take when service is terminated",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Default"},
				{Value: "1", Label: "RADIUS-Request"},
			},
			CoAApplicable:  true,
		},
		{
			Key:         "Called-Station-Id",
			AttributeID: 30,
			Label:       "Called Station ID",
			Description: "Phone number or station ID that was called",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"1234567890", "00:11:22:33:44:55"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Calling-Station-Id",
			AttributeID: 31,
			Label:       "Calling Station ID",
			Description: "Phone number or station ID that is calling",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"0987654321", "AA:BB:CC:DD:EE:FF"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "NAS-Identifier",
			AttributeID: 32,
			Label:       "NAS Identifier",
			Description: "String identifying the NAS",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"router1", "nas.example.com"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Proxy-State",
			AttributeID: 33,
			Label:       "Proxy State",
			Description: "State information to be maintained between proxy and server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Login-LAT-Service",
			AttributeID: 34,
			Label:       "Login LAT Service",
			Description: "System with which the user is to be connected by LAT",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Login-LAT-Node",
			AttributeID: 35,
			Label:       "Login LAT Node",
			Description: "Node with which the user is to be connected by LAT",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Login-LAT-Group",
			AttributeID: 36,
			Label:       "Login LAT Group",
			Description: "LAT group codes which this user is authorized to use",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Framed-AppleTalk-Link",
			AttributeID: 37,
			Label:       "Framed AppleTalk Link",
			Description: "AppleTalk network number for the user",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(65535),
		},
		{
			Key:         "Framed-AppleTalk-Network",
			AttributeID: 38,
			Label:       "Framed AppleTalk Network",
			Description: "AppleTalk network number for the user",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Framed-AppleTalk-Zone",
			AttributeID: 39,
			Label:       "Framed AppleTalk Zone",
			Description: "AppleTalk default zone for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
		},
		{
			Key:         "Acct-Status-Type",
			AttributeID: 40,
			Label:       "Acct Status Type",
			Description: "Type of accounting message",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "Start"},
				{Value: "2", Label: "Stop"},
				{Value: "3", Label: "Interim-Update"},
				{Value: "4", Label: "On"},
				{Value: "5", Label: "Off"},
				{Value: "6", Label: "Tunnel-Start"},
				{Value: "7", Label: "Tunnel-Stop"},
				{Value: "8", Label: "Tunnel-Reject"},
				{Value: "9", Label: "Tunnel-Link-Start"},
				{Value: "10", Label: "Tunnel-Link-Stop"},
				{Value: "11", Label: "Tunnel-Link-Reject"},
				{Value: "12", Label: "Failed"},
			},
		},
		{
			Key:         "Acct-Delay-Time",
			AttributeID: 41,
			Label:       "Acct Delay Time",
			Description: "Time in seconds that the client has been trying to send this request",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Input-Octets",
			AttributeID: 42,
			Label:       "Acct Input Octets",
			Description: "Number of octets received from the port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Output-Octets",
			AttributeID: 43,
			Label:       "Acct Output Octets",
			Description: "Number of octets sent to the port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Session-Id",
			AttributeID: 44,
			Label:       "Acct Session ID",
			Description: "Unique accounting session ID",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Acct-Authentic",
			AttributeID: 45,
			Label:       "Acct Authentic",
			Description: "How the user was authenticated",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "RADIUS"},
				{Value: "2", Label: "Local"},
				{Value: "3", Label: "Remote"},
				{Value: "4", Label: "Diameter"},
			},
		},
		{
			Key:         "Acct-Session-Time",
			AttributeID: 46,
			Label:       "Acct Session Time",
			Description: "Number of seconds the user has been logged in",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Input-Packets",
			AttributeID: 47,
			Label:       "Acct Input Packets",
			Description: "Number of packets received from the port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Output-Packets",
			AttributeID: 48,
			Label:       "Acct Output Packets",
			Description: "Number of packets sent to the port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Terminate-Cause",
			AttributeID: 49,
			Label:       "Acct Terminate Cause",
			Description: "How the session was terminated",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "User Request"},
				{Value: "2", Label: "Lost Carrier"},
				{Value: "3", Label: "Lost Service"},
				{Value: "4", Label: "Idle Timeout"},
				{Value: "5", Label: "Session Timeout"},
				{Value: "6", Label: "Admin Reset"},
				{Value: "7", Label: "Admin Reboot"},
				{Value: "8", Label: "Port Error"},
				{Value: "9", Label: "NAS Error"},
				{Value: "10", Label: "NAS Request"},
				{Value: "11", Label: "NAS Reboot"},
				{Value: "12", Label: "Port Unneeded"},
				{Value: "13", Label: "Port Preempted"},
				{Value: "14", Label: "Port Suspended"},
				{Value: "15", Label: "Service Unavailable"},
				{Value: "16", Label: "Callback"},
				{Value: "17", Label: "User Error"},
				{Value: "18", Label: "Host Request"},
			},
		},
		{
			Key:         "Acct-Multi-Session-Id",
			AttributeID: 50,
			Label:       "Acct Multi Session ID",
			Description: "Unique ID to link together multiple sessions",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Acct-Link-Count",
			AttributeID: 51,
			Label:       "Acct Link Count",
			Description: "Count of links in a multilink session",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Input-Gigawords",
			AttributeID: 52,
			Label:       "Acct Input Gigawords",
			Description: "Number of times the Acct-Input-Octets counter has wrapped around 2^32",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Acct-Output-Gigawords",
			AttributeID: 53,
			Label:       "Acct Output Gigawords",
			Description: "Number of times the Acct-Output-Octets counter has wrapped around 2^32",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Event-Timestamp",
			AttributeID: 55,
			Label:       "Event Timestamp",
			Description: "Timestamp when the event occurred",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAccounting,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "NAS-Port-Type",
			AttributeID: 61,
			Label:       "NAS Port Type",
			Description: "Type of physical port on the NAS",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Async"},
				{Value: "1", Label: "Sync"},
				{Value: "2", Label: "ISDN Sync"},
				{Value: "3", Label: "ISDN Async V.120"},
				{Value: "4", Label: "ISDN Async V.110"},
				{Value: "5", Label: "Virtual"},
				{Value: "6", Label: "PIAFS"},
				{Value: "7", Label: "HDLC Clear Channel"},
				{Value: "8", Label: "X.25"},
				{Value: "9", Label: "X.75"},
				{Value: "10", Label: "G.3 Fax"},
				{Value: "11", Label: "SDSL - Symmetric DSL"},
				{Value: "12", Label: "ADSL-CAP - ADSL Carrierless Amplitude Phase"},
				{Value: "13", Label: "ADSL-DMT - ADSL Discrete Multi-Tone"},
				{Value: "14", Label: "IDSL - ISDN Digital Subscriber Line"},
				{Value: "15", Label: "Ethernet"},
				{Value: "16", Label: "xDSL - Digital Subscriber Line of unknown type"},
				{Value: "17", Label: "Cable"},
				{Value: "18", Label: "Wireless - Other"},
				{Value: "19", Label: "Wireless - IEEE 802.11"},
				{Value: "20", Label: "Token-Ring"},
				{Value: "21", Label: "FDDI"},
				{Value: "22", Label: "Wireless - CDMA2000"},
				{Value: "23", Label: "Wireless - UMTS"},
				{Value: "24", Label: "Wireless - 1X-EV"},
				{Value: "25", Label: "IAPP"},
				{Value: "26", Label: "FTTP - Fiber to the Premises"},
				{Value: "27", Label: "Wireless - IEEE 802.16"},
				{Value: "28", Label: "Wireless - IEEE 802.20"},
				{Value: "29", Label: "Wireless - IEEE 802.22"},
				{Value: "30", Label: "PPPoA - PPP over ATM"},
				{Value: "31", Label: "PPPoEoA - PPP over Ethernet over ATM"},
				{Value: "32", Label: "PPPoEoE - PPP over Ethernet over Ethernet"},
				{Value: "33", Label: "PPPoEoVLAN - PPP over Ethernet over VLAN"},
				{Value: "34", Label: "PPPoEoQinQ - PPP over Ethernet over QinQ"},
				{Value: "35", Label: "xPON - Passive Optical Network"},
				{Value: "36", Label: "Wireless - XGP"},
				{Value: "37", Label: "WiMAX Pre-Release 8"},
				{Value: "38", Label: "WIMAX Release 8"},
				{Value: "39", Label: "WIMAX 2"},
				{Value: "40", Label: "CAPWAP"},
				{Value: "41", Label: "WIMAX Relay"},
			},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Connect-Info",
			AttributeID: 77,
			Label:       "Connect Info",
			Description: "Information about the connection",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"100Mbps", "1Gbps Full Duplex"},
		},
		{
			Key:         "NAS-Port-Id",
			AttributeID: 87,
			Label:       "NAS Port ID",
			Description: "Text identifier for the NAS port",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"eth0", "ge-0/0/0", "FastEthernet0/1"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Framed-Pool",
			AttributeID: 88,
			Label:       "Framed Pool",
			Description: "IP pool from which to assign an IP address",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"pool1", "default-pool"},
			CoAApplicable:  true,
		},
		{
			Key:         "NAS-IPv6-Address",
			AttributeID: 95,
			Label:       "NAS IPv6 Address",
			Description: "The IPv6 address of the Network Access Server",
			DataType:    RadiusDataTypeIPv6,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"2001:db8::1"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Framed-Interface-Id",
			AttributeID: 96,
			Label:       "Framed Interface ID",
			Description: "IPv6 interface identifier for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Pattern:     `^[0-9a-fA-F:]+$`,
			Examples:    []string{"0:0:0:1"},
			CoAApplicable:  true,
			DMApplicable:   true,
		},
		{
			Key:         "Framed-IPv6-Prefix",
			AttributeID: 97,
			Label:       "Framed IPv6 Prefix",
			Description: "IPv6 prefix to be configured for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Pattern:     `^[0-9a-fA-F:]+/\d{1,3}$`,
			Examples:    []string{"2001:db8::/64"},
			CoAApplicable:  true,
		},
		{
			Key:         "Login-IPv6-Host",
			AttributeID: 98,
			Label:       "Login IPv6 Host",
			Description: "IPv6 system with which to connect the user",
			DataType:    RadiusDataTypeIPv6,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"2001:db8::10"},
		},
		{
			Key:         "Framed-IPv6-Route",
			AttributeID: 99,
			Label:       "Framed IPv6 Route",
			Description: "IPv6 routing information to be configured for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryRouting,
			Required:    false,
			Pattern:     `^[0-9a-fA-F:]+/\d{1,3}(\s+[0-9a-fA-F:]+(\s+\d+)?)?$`,
			Examples:    []string{"2001:db8:1::/48", "2001:db8:2::/48 2001:db8::1 1"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Framed-IPv6-Pool",
			AttributeID: 100,
			Label:       "Framed IPv6 Pool",
			Description: "IPv6 pool from which to assign a prefix",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"ipv6-pool1"},
			CoAApplicable:  true,
		},
		{
			Key:         "Delegated-IPv6-Prefix",
			AttributeID: 123,
			Label:       "Delegated IPv6 Prefix",
			Description: "IPv6 prefix to delegate to user's local network (DHCPv6-PD)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Pattern:     `^[0-9a-fA-F:]+/\d{1,3}$`,
			Examples:    []string{"2001:db8:a::/48"},
			CoAApplicable:  true,
		},
		{
			Key:         "Tunnel-Type",
			AttributeID: 64,
			Label:       "Tunnel Type",
			Description: "The tunneling protocol being used",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "PPTP"},
				{Value: "2", Label: "L2TP"},
				{Value: "3", Label: "L2F"},
				{Value: "4", Label: "ATMP"},
				{Value: "5", Label: "VLAN"},
				{Value: "6", Label: "IP"},
				{Value: "7", Label: "IP-in-IP"},
				{Value: "8", Label: "GRE"},
				{Value: "9", Label: "IPSec"},
				{Value: "10", Label: "VXLAN"},
				{Value: "11", Label: "NVGRE"},
				{Value: "12", Label: "MPLS"},
				{Value: "13", Label: "MPLS-in-IP"},
				{Value: "14", Label: "MPLS-in-GRE"},
				{Value: "15", Label: "IPSec-in-GRE"},
				{Value: "16", Label: "Wireless (WLAN)"},
				{Value: "17", Label: "Wireless (WPAN)"},
			},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Tunnel-Medium-Type",
			AttributeID: 65,
			Label:       "Tunnel Medium Type",
			Description: "The transport medium for the tunnel",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Options: []FieldOption{
				{Value: "1", Label: "IPv4"},
				{Value: "2", Label: "IPv6"},
				{Value: "3", Label: "NSAP"},
				{Value: "4", Label: "HDLC"},
				{Value: "5", Label: "BBN 1822"},
				{Value: "6", Label: "802"},
				{Value: "7", Label: "E.163"},
				{Value: "8", Label: "E.164"},
				{Value: "9", Label: "F.69"},
				{Value: "10", Label: "X.121"},
				{Value: "11", Label: "IPX"},
				{Value: "12", Label: "Appletalk"},
				{Value: "13", Label: "Decnet IV"},
				{Value: "14", Label: "Banyan Vines"},
				{Value: "15", Label: "E.164 with NSAP subaddress"},
			},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Tunnel-Client-Endpoint",
			AttributeID: 66,
			Label:       "Tunnel Client Endpoint",
			Description: "IP address of the tunnel client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Examples:    []string{"192.168.1.1", "2001:db8::1"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Tunnel-Server-Endpoint",
			AttributeID: 67,
			Label:       "Tunnel Server Endpoint",
			Description: "IP address of the tunnel server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Examples:    []string{"10.0.0.1", "2001:db8::2"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Tunnel-Password",
			AttributeID: 69,
			Label:       "Tunnel Password",
			Description: "Password for authenticating to the tunnel server",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			CoAApplicable:  true,
			MultiValue:     true,
		},
		{
			Key:         "Tunnel-Private-Group-Id",
			AttributeID: 81,
			Label:       "Tunnel Private Group ID",
			Description: "Group ID for the tunnel",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			Examples:    []string{"100", "VLAN100"},
			CoAApplicable:  true,
			MultiValue:     true,
		},
	},
}
