package provider

// radiusVendorRuckus holds the RADIUS attribute dictionary for RUCKUS.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorRuckus = VendorDictionaryInfo{
	Value:       "RUCKUS",
	Label:       "Ruckus Networks (CommScope)",
	Description: "Ruckus Networks RADIUS VSA (Vendor ID: 25053). Used with Ruckus SmartZone, ZoneDirector, and Unleashed APs.",
	VendorID:    25053,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Ruckus-User-Groups",
			AttributeID:    1,
			Label:       "User Groups",
			Description: "Comma-separated list of user group names for policy matching",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(253),
			Examples:    []string{"employee,wifi-corp", "guest"},
		},
		{
			Key:         "Ruckus-Auth-Type",
			AttributeID:    2,
			Label:       "Auth Type",
			Description: "Authentication method used for this client",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Options: []FieldOption{
				{Value: "0", Label: "Not Set"},
				{Value: "1", Label: "MAC Authentication"},
				{Value: "2", Label: "802.1X"},
				{Value: "3", Label: "WISPr"},
			},
		},
		{
			Key:         "Ruckus-WLAN-Name",
			AttributeID:    3,
			Label:       "WLAN Name",
			Description: "Name of the WLAN/SSID the client associated with",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			MaxLength:   intPtr(32),
			Examples:    []string{"Corp-WiFi", "Guest"},
		},
		{
			Key:         "Ruckus-SSID",
			AttributeID:    5,
			Label:       "SSID",
			Description: "SSID broadcast name the client connected to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			MaxLength:   intPtr(32),
			Examples:    []string{"Corp-WiFi", "IoT-Net"},
		},
		{
			Key:         "Ruckus-BSSID",
			AttributeID:    26,
			Label:       "BSSID",
			Description: "MAC address of the AP radio the client connected to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			Pattern:     `^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$`,
			Examples:    []string{"AA:BB:CC:DD:EE:FF"},
		},
		{
			Key:         "Ruckus-Sta-RSSI",
			AttributeID:    6,
			Label:       "Station RSSI",
			Description: "Received Signal Strength Indicator of the client station in dBm",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryMobility,
			MinValue:    float64Ptr(-120),
			MaxValue:    float64Ptr(0),
			Examples:    []string{"-65", "-80"},
		},
		{
			Key:         "Ruckus-Vlan-ID",
			AttributeID:    7,
			Label:       "VLAN ID",
			Description: "VLAN to assign to the wireless client after authentication",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Ruckus-Standby-Vlan-ID",
			AttributeID:    29,
			Label:       "Standby VLAN ID",
			Description: "Fallback VLAN ID when the primary VLAN is unavailable",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"999"},
		},
		{
			Key:         "Ruckus-URL-Redirection",
			AttributeID:    25,
			Label:       "URL Redirection",
			Description: "URL to redirect the client to after MAC auth (captive portal)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Pattern:     `^https?://[^\s]+$`,
			Examples:    []string{"https://portal.example.com/welcome"},
		},
		{
			Key:         "Ruckus-Rate-Limit-Up",
			AttributeID:    22,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200"},
		},
		{
			Key:         "Ruckus-Rate-Limit-Down",
			AttributeID:    21,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480", "102400"},
		},
		{
			Key:         "Ruckus-Session-Volume-Quota",
			AttributeID:    28,
			Label:       "Session Volume Quota",
			Description: "Total bidirectional data quota for the session in bytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10737418240", "0"},
		},
		{
			Key:         "Ruckus-Role",
			AttributeID:    31,
			Label:       "Role",
			Description: "User role name used for policy enforcement in SmartZone",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"employee", "guest", "contractor"},
		},
		{
			Key:         "Ruckus-Tenant-ID",
			AttributeID:    30,
			Label:       "Tenant ID",
			Description: "Multi-tenant identifier for SaaS or hosted SmartZone deployments",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(64),
			Examples:    []string{"tenant-abc", "org-123"},
		},
		{
			Key:         "Ruckus-Policy-Group",
			AttributeID:    23,
			Label:       "Policy Group",
			Description: "Policy group name applied to the authenticated client session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"corp-policy", "guest-policy"},
		},
		{
			Key:         "Ruckus-Profile-Name",
			AttributeID:    24,
			Label:       "Profile Name",
			Description: "Device profile or client profile name for device classification",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"byod-profile", "iot-profile"},
		},
		{
			Key:         "Ruckus-Location-Information",
			AttributeID:    27,
			Label:       "Location Information",
			Description: "Human-readable location string for the AP (e.g. building/floor)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(253),
			Examples:    []string{"Building-A, Floor-3", "HQ-ServerRoom"},
		},
	},
}