package provider

// radiusVendorAruba holds the RADIUS attribute dictionary for ARUBA.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorAruba = VendorDictionaryInfo{
	Value:       "ARUBA",
	Label:       "Aruba Networks (HPE)",
	Description: "Aruba Networks RADIUS VSA (Vendor ID: 14823). Used with Aruba wireless controllers, switches, and ClearPass Policy Manager.",
	VendorID:    14823,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Aruba-User-Role",
			AttributeID:    1,
			Label:       "User Role",
			Description: "Aruba firewall role (policy) to assign to the authenticated user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"employee", "guest", "contractor"},
		},
		{
			Key:         "Aruba-User-Vlan",
			AttributeID:    2,
			Label:       "User VLAN",
			Description: "VLAN ID to assign to the user after authentication",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200", "999"},
		},
		{
			Key:         "Aruba-Priv-Admin-User",
			AttributeID:    3,
			Label:       "Privileged Admin User",
			Description: "Grants the user privileged administrator rights on the Aruba device (non-zero = enabled)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(1),
			Examples:    []string{"1"},
		},
		{
			Key:         "Aruba-Template-User",
			AttributeID:    4,
			Label:       "Template User",
			Description: "Existing local user account from which to clone role settings",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"template-employee", "template-guest"},
		},
		{
			Key:         "Aruba-Bandwidth-Max-Up",
			Label:       "Bandwidth Max Up",
			Description: "Maximum upstream (client-to-network) bandwidth in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200", "102400"},
		},
		{
			Key:         "Aruba-Bandwidth-Max-Down",
			Label:       "Bandwidth Max Down",
			Description: "Maximum downstream (network-to-client) bandwidth in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480", "102400", "204800"},
		},
		{
			Key:         "Aruba-Bandwidth-Bursting-Disable",
			Label:       "Bandwidth Bursting Disable",
			Description: "Disable bandwidth bursting for this user (1 = disabled)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(1),
			Examples:    []string{"1"},
		},
		{
			Key:         "Aruba-AirGroup-User-Name",
			Label:       "AirGroup User Name",
			Description: "AirGroup username used for mDNS/Bonjour device sharing policies",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			Examples:    []string{"john.doe@example.com"},
		},
		{
			Key:         "Aruba-AirGroup-Shared-Role",
			Label:       "AirGroup Shared Role",
			Description: "AirGroup user role used to control shared device visibility",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			Examples:    []string{"employee-shared", "it-shared"},
		},
		{
			Key:         "Aruba-MPSK-Passphrase",
			Label:       "MPSK Passphrase",
			Description: "Multi Pre-Shared Key (MPSK) passphrase assigned to this client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MinLength:   intPtr(8),
			MaxLength:   intPtr(63),
		},
		{
			Key:         "Aruba-Framed-IPv6-Address",
			Label:       "Framed IPv6 Address",
			Description: "Statically assigned IPv6 address for the user session",
			DataType:    RadiusDataTypeIPv6,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"2001:db8::100"},
		},
		{
			Key:         "Aruba-Port-Id",
			Label:       "Port ID",
			Description: "Physical port identifier on an Aruba switch (used in wired 802.1X)",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Examples:    []string{"1/1/1", "0/1", "GE0/0/1"},
		},
	},
}
