package provider

// radiusVendorEricssonSsr holds the RADIUS attribute dictionary for ERICSSON_SSR.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorEricssonSsr = VendorDictionaryInfo{
	Value:       "ERICSSON_SSR",
	Label:       "Ericsson SmartEdge (Redback SSR)",
	Description: "Ericsson (formerly Redback) SmartEdge SSR RADIUS VSA (Vendor ID: 2352). Used in ISP BNG and CGNAT deployments on SmartEdge/SE800 platforms.",
	VendorID:    2352,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "RB-NAS-Port-Name",
			AttributeID:    8,
			Label:       "NAS Port Name",
			Description: "Textual name of the NAS interface the session arrived on",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(253),
			Examples:    []string{"atm 1/1/1:100.101", "eth 1/1:100"},
		},
		{
			Key:         "RB-Subscriber-ID",
			AttributeID:    1,
			Label:       "Subscriber ID",
			Description: "Unique identifier for the subscriber session used in accounting correlation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(253),
			Examples:    []string{"sub-0001-abc", "cust-00112233"},
		},
		{
			Key:         "RB-Context-Name",
			AttributeID:    2,
			Label:       "Context Name",
			Description: "VRF / routing context the subscriber session is bound to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"local", "isp-vrf1"},
		},
		{
			Key:         "RB-Policy-Name",
			AttributeID:    3,
			Label:       "Policy Name",
			Description: "QoS/traffic-management policy applied to the subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"pol-10m-down", "pol-100m-business"},
		},
		{
			Key:         "RB-Rate-Limit-Rate",
			AttributeID:    5,
			Label:       "Rate Limit Rate",
			Description: "Committed rate limit for the subscriber in bps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10000000", "100000000"},
		},
		{
			Key:         "RB-Rate-Limit-Burst",
			AttributeID:    6,
			Label:       "Rate Limit Burst",
			Description: "Burst size above the committed rate in bytes",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"1500000", "10000000"},
		},
		{
			Key:         "RB-Police-Rate",
			AttributeID:    7,
			Label:       "Police Rate",
			Description: "Hard policer rate applied to the subscriber in bps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20000000", "200000000"},
		},
		{
			Key:         "RB-Tunnel-Domain",
			AttributeID:    9,
			Label:       "Tunnel Domain",
			Description: "L2TP tunnel domain name the subscriber is bound to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(64),
			Examples:    []string{"l2tp-domain-1"},
		},
		{
			Key:         "RB-Tunnel-Group",
			AttributeID:    10,
			Label:       "Tunnel Group",
			Description: "L2TP tunnel group name for load-balancing across multiple LNS",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(64),
			Examples:    []string{"lns-grp-core", "lns-grp-backup"},
		},
		{
			Key:         "RB-Tunnel-Max-Sessions",
			AttributeID:    11,
			Label:       "Tunnel Max Sessions",
			Description: "Maximum concurrent sessions allowed in this L2TP tunnel",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			Examples:    []string{"500", "1000"},
		},
		{
			Key:         "RB-Bind-Type",
			AttributeID:    12,
			Label:       "Bind Type",
			Description: "Session binding type on the SmartEdge",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "Auth-Only"},
				{Value: "2", Label: "Subscriber"},
				{Value: "3", Label: "Multicast"},
			},
		},
		{
			Key:         "RB-Category-Map",
			AttributeID:    4,
			Label:       "Category Map",
			Description: "Traffic category map name for DPI/classification",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(64),
			Examples:    []string{"cat-map-default", "cat-map-voip"},
		},
	},
}