package provider

// radiusVendorAerohive holds the RADIUS attribute dictionary for AEROHIVE.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorAerohive = VendorDictionaryInfo{
	Value:       "AEROHIVE",
	Label:       "Aerohive / Extreme Networks",
	Description: "Aerohive Networks RADIUS VSA (Vendor ID: 26928). Now ExtremeCloud IQ (XIQ). Used with Hive APs and ExtremeCloud-managed devices.",
	VendorID:    26928,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Aerohive-SSID",
			AttributeID:    1,
			Label:       "SSID",
			Description: "Name of the SSID the client is connected to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryMobility,
			MaxLength:   intPtr(32),
			Examples:    []string{"Corp-Hive", "Guest-Hive"},
		},
		{
			Key:         "Aerohive-QoS-Policy",
			AttributeID:    7,
			Label:       "QoS Policy",
			Description: "QoS policy profile name applied to the client session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"qos-gold", "qos-best-effort"},
		},
		{
			Key:         "Aerohive-Rate-Limit-Down",
			AttributeID:    4,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200"},
		},
		{
			Key:         "Aerohive-Rate-Limit-Up",
			AttributeID:    5,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream bandwidth for the client in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"5120", "20480"},
		},
		{
			Key:         "Aerohive-User-Profile",
			AttributeID:    3,
			Label:       "User Profile",
			Description: "User profile (firewall/policy context) to assign to the client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"employee-profile", "guest-profile"},
		},
		{
			Key:         "Aerohive-User-Profile-Override",
			AttributeID:    9,
			Label:       "User Profile Override",
			Description: "Override the default user profile for this specific client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"contractor-override"},
		},
		{
			Key:         "Aerohive-VLAN-ID",
			AttributeID:    2,
			Label:       "VLAN ID",
			Description: "VLAN to assign to the client after successful authentication",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Aerohive-Captive-Web-Portal",
			AttributeID:    8,
			Label:       "Captive Web Portal",
			Description: "Name of the captive web portal profile to redirect the client to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"guest-portal", "sponsored-portal"},
		},
		{
			Key:         "Aerohive-Client-Type",
			AttributeID:    6,
			Label:       "Client Type",
			Description: "Device/client type classification for policy matching",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryGeneral,
			Options: []FieldOption{
				{Value: "0", Label: "Unknown"},
				{Value: "1", Label: "Phone"},
				{Value: "2", Label: "Laptop"},
				{Value: "3", Label: "Tablet"},
				{Value: "4", Label: "IoT Device"},
			},
		},
	},
}

