package provider

// radiusVendorNokiaSrOs holds the RADIUS attribute dictionary for NOKIA_SR_OS.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorNokiaSrOs = VendorDictionaryInfo{
	Value:       "NOKIA_SR_OS",
	Label:       "Nokia SR-OS (Alcatel-Lucent)",
	Description: "Nokia (formerly Alcatel-Lucent) SR-OS RADIUS VSA (Vendor ID: 6527). Widely used in ISP BNG and CGNAT deployments on 7750 SR / 7450 ESS platforms.",
	VendorID:    6527,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Alc-Primary-Dns",
			AttributeID:    5,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the PPPoE/IPoE subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "Alc-Secondary-Dns",
			AttributeID:    6,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "Alc-Subsc-ID-Str",
			AttributeID:    1,
			Label:       "Subscriber ID",
			Description: "Subscriber identifier string used for session tracking and accounting correlation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(253),
			Examples:    []string{"sub-00112233", "customer-0001"},
		},
		{
			Key:         "Alc-Subsc-Prof-Str",
			AttributeID:    2,
			Label:       "Subscriber Profile",
			Description: "Subscriber profile name defining session-level QoS and service parameters",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(253),
			Examples:    []string{"prof-residential-100m", "prof-business-1g"},
		},
		{
			Key:         "Alc-SLA-Prof-Str",
			AttributeID:    3,
			Label:       "SLA Profile",
			Description: "SLA profile name defining per-host QoS shaping/scheduling",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(253),
			Examples:    []string{"sla-100m-10m", "sla-1g-100m"},
		},
		{
			Key:         "Alc-Ip-Pool",
			AttributeID:    8,
			Label:       "IP Pool",
			Description: "Local IP address pool name from which to assign the subscriber's IP",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"pool-residential", "pool-cgnat-public"},
		},
		{
			Key:         "Alc-Default-Router",
			AttributeID:    9,
			Label:       "Default Router",
			Description: "Default gateway IP address pushed to the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"10.0.0.1", "100.64.0.1"},
		},
		{
			Key:         "Alc-Nat-Policy-Name",
			AttributeID:    135,
			Label:       "NAT Policy Name",
			Description: "CGNAT policy name applied to the subscriber — controls NAT pool, port blocks, and hairpinning",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"cgnat-policy-default", "nat-pol-lsn"},
		},
		{
			Key:         "Alc-Nat-Pool-Name",
			AttributeID:    134,
			Label:       "NAT Pool Name",
			Description: "Explicit public IP pool from which CGNAT addresses are allocated",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"nat-pool-1", "cgnat-outside"},
		},
		{
			Key:         "Alc-Tunnel-Group",
			AttributeID:    10,
			Label:       "Tunnel Group",
			Description: "L2TP or GRE tunnel group the subscriber session is bound to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(32),
			Examples:    []string{"l2tp-grp-1", "gre-grp-core"},
		},
		{
			Key:         "Alc-Tos-Marking-State",
			AttributeID:    11,
			Label:       "ToS Marking State",
			Description: "Controls whether the subscriber's traffic ToS/DSCP bits may be remarked",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryQoS,
			Options: []FieldOption{
				{Value: "0", Label: "Trusted"},
				{Value: "1", Label: "Untrusted"},
			},
		},
		{
			Key:         "Alc-SLAAC-IPv6-Pool",
			AttributeID:    173,
			Label:       "SLAAC IPv6 Pool",
			Description: "IPv6 prefix pool used for SLAAC address assignment to the subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"ipv6-pool-slaac"},
		},
		{
			Key:         "Alc-Delegated-IPv6-Pool",
			AttributeID:    170,
			Label:       "Delegated IPv6 Pool",
			Description: "IPv6 prefix pool used for DHCPv6-PD prefix delegation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(32),
			Examples:    []string{"ipv6-pd-pool-56", "ipv6-pd-pool-48"},
		},
		{
			Key:         "Alc-Force-DHCP-Relay",
			AttributeID:    4,
			Label:       "Force DHCP Relay",
			Description: "Force the BNG to act as DHCP relay for this subscriber (1 = force)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(1),
			Examples:    []string{"1"},
		},
	},
}