package provider

// radiusVendorHpProcurve holds the RADIUS attribute dictionary for HP_PROCURVE.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorHpProcurve = VendorDictionaryInfo{
	Value:       "HP_PROCURVE",
	Label:       "HP / HPE ProCurve & Comware",
	Description: "HP / HPE ProCurve and Comware RADIUS VSA (Vendor ID: 11). Used with HPE switches and access points for wired 802.1X, VLAN assignment, and management access.",
	VendorID:    11,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "HP-Privilege-Level",
			AttributeID:    1,
			Label:       "Privilege Level",
			Description: "CLI privilege level granted to the administrator (0 = minimum, 15 = maximum)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"15", "7", "1"},
		},
		{
			Key:         "HP-Command-String",
			AttributeID:    2,
			Label:       "Command String",
			Description: "CLI command string the user is permitted to execute",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(253),
			Examples:    []string{"display .*", "show interfaces"},
		},
		{
			Key:         "HP-Port-Client-Limit-Dot1x",
			AttributeID:    23,
			Label:       "Port Client Limit 802.1X",
			Description: "Maximum number of 802.1X authenticated clients allowed on the port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(32),
			Examples:    []string{"1", "4", "8"},
		},
		{
			Key:         "HP-Bandwidth-Max-Ingress",
			AttributeID:    3,
			Label:       "Bandwidth Max Ingress",
			Description: "Maximum ingress (client-to-switch) bandwidth rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "102400"},
		},
		{
			Key:         "HP-Bandwidth-Max-Egress",
			AttributeID:    4,
			Label:       "Bandwidth Max Egress",
			Description: "Maximum egress (switch-to-client) bandwidth rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"51200", "204800"},
		},
		{
			Key:         "HP-Cos",
			AttributeID:    7,
			Label:       "Class of Service",
			Description: "802.1p Class of Service value to mark on the client's traffic",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(7),
			Examples:    []string{"0", "4", "6"},
		},
		{
			Key:         "HP-Nas-Rules",
			AttributeID:    5,
			Label:       "NAS Rules",
			Description: "Named ACL or policy rule set applied to the authenticated port",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(253),
			Examples:    []string{"acl-employee", "acl-guest"},
		},
		{
			Key:         "HP-User-Role",
			AttributeID:    25,
			Label:       "User Role",
			Description: "Comware / IMC user role name controlling device management access",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"network-admin", "network-operator", "guest-manager"},
		},
		{
			Key:         "HP-Voice-VLAN-Id",
			AttributeID:    8,
			Label:       "Voice VLAN ID",
			Description: "VLAN ID to use for voice traffic on the authenticated port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"10", "100"},
		},
	},
}
