package provider

// radiusVendorBrocadeIcx holds the RADIUS attribute dictionary for BROCADE_ICX.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorBrocadeIcx = VendorDictionaryInfo{
	Value:       "BROCADE_ICX",
	Label:       "Brocade / Ruckus ICX Switches",
	Description: "Brocade (now Ruckus/CommScope) ICX switch RADIUS VSA (Vendor ID: 1991). Used for 802.1X wired authentication, management access, and VLAN assignment.",
	VendorID:    1991,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Brocade-Auth-Role",
			AttributeID:    1,
			Label:       "Auth Role",
			Description: "Management access role granted to the administrator",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Options: []FieldOption{
				{Value: "0", Label: "Disabled"},
				{Value: "1", Label: "Port Configuration"},
				{Value: "2", Label: "Read Only"},
				{Value: "3", Label: "Read Write"},
				{Value: "4", Label: "Super User"},
			},
		},
		{
			Key:         "Brocade-Privilege-Level",
			AttributeID:    2,
			Label:       "Privilege Level",
			Description: "CLI privilege level on the ICX device (0 = lowest, 15 = highest)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"15", "5", "0"},
		},
		{
			Key:         "Brocade-Exec-Privilege-Level",
			AttributeID:    5,
			Label:       "Exec Privilege Level",
			Description: "Privilege level for EXEC mode commands",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(15),
			Examples:    []string{"15", "7"},
		},
		{
			Key:         "Brocade-Port-VLAN-ID",
			AttributeID:    7,
			Label:       "Port VLAN ID",
			Description: "VLAN ID to assign to the authenticated port (untagged)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Brocade-MAC-Auth-VLAN",
			AttributeID:    6,
			Label:       "MAC Auth VLAN",
			Description: "VLAN to assign during MAC authentication bypass (MAB)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"999", "100"},
		},
		{
			Key:         "Brocade-Voice-Phone-VLAN",
			AttributeID:    8,
			Label:       "Voice Phone VLAN",
			Description: "VLAN ID for voice traffic on the authenticated port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"10", "20"},
		},
	},
}