package provider

// radiusVendorExtremeXos holds the RADIUS attribute dictionary for EXTREME_XOS.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorExtremeXos = VendorDictionaryInfo{
	Value:       "EXTREME_XOS",
	Label:       "Extreme Networks ExtremeXOS",
	Description: "Extreme Networks ExtremeXOS RADIUS VSA (Vendor ID: 1916). Used with Extreme campus and data-centre switches for 802.1X, management access, and QoS. Separate from Aerohive/ExtremeCloud (26928).",
	VendorID:    1916,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Extreme-CLI-Authorization",
			AttributeID:    201,
			Label:       "CLI Authorization",
			Description: "Enables RADIUS-based authorisation of CLI commands for admin users",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Options: []FieldOption{
				{Value: "0", Label: "Disabled"},
				{Value: "1", Label: "Enabled"},
			},
		},
		{
			Key:         "Extreme-Shell-Command",
			AttributeID:    202,
			Label:       "Shell Command",
			Description: "ExtremeXOS CLI command the user is authorised to run",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(253),
			Examples:    []string{"show ports", "show vlan"},
		},
		{
			Key:         "Extreme-Netlogin-Vlan",
			AttributeID:    203,
			Label:       "Netlogin VLAN",
			Description: "VLAN name to assign to the port after 802.1X / MAC Netlogin authentication",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(32),
			Examples:    []string{"corp", "guest", "iot"},
		},
		{
			Key:         "Extreme-Netlogin-Vlan-Tag",
			AttributeID:    207,
			Label:       "Netlogin VLAN Tag",
			Description: "VLAN ID (numeric) to assign after Netlogin authentication",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Extreme-Netlogin-URL",
			AttributeID:    204,
			Label:       "Netlogin Redirect URL",
			Description: "URL to redirect the client to for web-based Netlogin",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Pattern:     `^https?://[^\s]+$`,
			Examples:    []string{"https://portal.example.com"},
		},
		{
			Key:         "Extreme-Netlogin-URL-Desc",
			AttributeID:    205,
			Label:       "Netlogin URL Description",
			Description: "Human-readable description of the redirect URL shown to the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"Guest Portal", "Self-Registration"},
		},
		{
			Key:         "Extreme-Netlogin-Extended-Vlan",
			AttributeID:    206,
			Label:       "Netlogin Extended VLAN",
			Description: "Extended VLAN assignment string supporting multiple VLANs and roles",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryTunneling,
			MaxLength:   intPtr(253),
			Examples:    []string{"VLAN=100;ROLE=employee"},
		},
		{
			Key:         "Extreme-Policy-Name",
			AttributeID:    208,
			Label:       "Policy Name",
			Description: "ExtremeXOS policy profile name applied to the authenticated client port",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"employee-policy", "guest-policy"},
		},
		{
			Key:         "Extreme-User-Location",
			AttributeID:    209,
			Label:       "User Location",
			Description: "Physical location information reported by the switch for the authenticated user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(64),
			Examples:    []string{"Building-A-Floor-2", "Rack-12"},
		},
	},
}