package provider

// radiusVendorMikrotik holds the RADIUS attribute dictionary for MIKROTIK.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorMikrotik = VendorDictionaryInfo{
	Value:       "MIKROTIK",
	Label:       "MikroTik",
	Description: "MikroTik RouterOS specific RADIUS attributes (Vendor ID: 14988).",
	VendorID:    14988,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Mikrotik-Rate-Limit",
			AttributeID:    8,
			Label:       "Rate Limit",
			Description: "Bandwidth limit for the user. Format: rx-rate[/tx-rate] [rx-burst-rate[/tx-burst-rate] [rx-burst-threshold[/tx-burst-threshold] [rx-burst-time[/tx-burst-time] [priority] [rx-rate-min[/tx-rate-min]]]]",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			Required:    false,
			Pattern:     `^\d+[kKmMgG](\/\d+[kKmMgG])?(\s+\d+[kKmMgG](\/\d+[kKmMgG])?(\s+\d+[kKmMgG](\/\d+[kKmMgG])?(\s+\d+[kKmMgG](\/\d+[kKmMgG])?(\s+\d+(\s+\d+[kKmMgG](\/\d+[kKmMgG])?)?)?)?)?$`,
			Examples:    []string{"10M/10M", "5M/10M 10M/20M 5M/10M 10s 5", "1M/2M 2M/4M 1M/2M 10s 8 512k/1M"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Address-List",
			AttributeID:    19,
			Label:       "Address List",
			Description: "Firewall address list to which user is added",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			Required:    false,
			Examples:    []string{"allowed", "blocked", "premium"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Group",
			AttributeID:    3,
			Label:       "User Group",
			Description: "MikroTik User group name",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"default", "premium", "trial"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Wireless-Enc-Algo",
			AttributeID:    6,
			Label:       "Wireless Encryption Algorithm",
			Description: "Wireless encryption algorithm for the user",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "none", Label: "None"},
				{Value: "40bit-wep", Label: "40-bit WEP"},
				{Value: "104bit-wep", Label: "104-bit WEP"},
				{Value: "aes-ccm", Label: "AES-CCM"},
				{Value: "tkip", Label: "TKIP"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Enc-Key",
			AttributeID:    7,
			Label:       "Wireless Encryption Key",
			Description: "Wireless encryption key for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(64),
		},
		{
			Key:         "Mikrotik-Wireless-Psk",
			AttributeID:    16,
			Label:       "Wireless PSK",
			Description: "Wireless Pre-Shared Key for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(8),
			MaxLength:   intPtr(64),
		},
		{
			Key:         "Mikrotik-Wireless-Vlan-Id",
			AttributeID:    20,
			Label:       "Wireless VLAN ID",
			Description: "VLAN ID to assign to wireless client",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			Required:    false,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Mikrotik-Wireless-Vlan-Psk",
			AttributeID:    35,
			Label:       "Wireless VLAN PSK",
			Description: "PSK for VLAN wireless client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(8),
			MaxLength:   intPtr(64),
		},
		{
			Key:         "Mikrotik-Wireless-Vlan-Enc-Algo",
			AttributeID:    36,
			Label:       "Wireless VLAN Encryption Algorithm",
			Description: "Encryption algorithm for VLAN wireless client",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "none", Label: "None"},
				{Value: "aes-ccm", Label: "AES-CCM"},
				{Value: "tkip", Label: "TKIP"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Vlan-Enc-Key",
			AttributeID:    37,
			Label:       "Wireless VLAN Encryption Key",
			Description: "Encryption key for VLAN wireless client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(64),
		},
		{
			Key:         "Mikrotik-Wireless-Multicast-Key",
			AttributeID:    24,
			Label:       "Wireless Multicast Key",
			Description: "Multicast encryption key for wireless",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(64),
		},
		{
			Key:         "Mikrotik-Wireless-Multicast-Encryption",
			AttributeID:    25,
			Label:       "Wireless Multicast Encryption",
			Description: "Multicast encryption type for wireless",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "none", Label: "None"},
				{Value: "aes-ccm", Label: "AES-CCM"},
				{Value: "tkip", Label: "TKIP"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Fast-Transition",
			AttributeID:    33,
			Label:       "Wireless Fast Transition",
			Description: "Enable 802.11r Fast Transition for the client",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Pmk-Caching",
			AttributeID:    31,
			Label:       "Wireless PMK Caching",
			Description: "Enable PMK caching for the client",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Group-Key-Update",
			AttributeID:    29,
			Label:       "Wireless Group Key Update",
			Description: "Group key update interval in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(60),
			MaxValue:    float64Ptr(86400),
			Examples:    []string{"3600", "7200"},
		},
		{
			Key:         "Mikrotik-Wireless-Preauth-Timeout",
			AttributeID:    30,
			Label:       "Wireless Preauth Timeout",
			Description: "Preauthentication timeout in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(3600),
			Examples:    []string{"30", "60"},
		},
		{
			Key:         "Mikrotik-Realm",
			AttributeID:    9,
			Label:       "Realm",
			Description: "Realm name for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Examples:    []string{"example.com", "isp.net"},
		},
		{
			Key:         "Mikrotik-Recv-Limit",
			AttributeID:    1,
			Label:       "Receive Limit",
			Description: "Total receive limit in bytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10737418240", "5368709120"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Xmit-Limit",
			AttributeID:    2,
			Label:       "Transmit Limit",
			Description: "Total transmit limit in bytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10737418240", "5368709120"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Recv-Limit-Gigawords",
			AttributeID:    14,
			Label:       "Receive Limit Gigawords",
			Description: "High 32 bits of receive limit",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Xmit-Limit-Gigawords",
			AttributeID:    15,
			Label:       "Transmit Limit Gigawords",
			Description: "High 32 bits of transmit limit",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Total-Limit",
			AttributeID:    17,
			Label:       "Total Limit",
			Description: "Total (tx+rx) limit in bytes (0 = unlimited)",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"21474836480", "10737418240"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Total-Limit-Gigawords",
			AttributeID:    18,
			Label:       "Total Limit Gigawords",
			Description: "High 32 bits of total limit",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			Required:    false,
			MinValue:    float64Ptr(0),
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Session-Timeout",
			Label:       "Session Timeout",
			Description: "Maximum session time in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"3600", "7200"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Idle-Timeout",
			Label:       "Idle Timeout",
			Description: "Maximum idle time in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"300", "600"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Wireless-Forward",
			AttributeID:    4,
			Label:       "Wireless Forward",
			Description: "Enable wireless forwarding for the client",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Client-To-Client-Forwarding",
			AttributeID:    21,
			Label:       "Wireless Client-to-Client Forwarding",
			Description: "Enable client-to-client forwarding",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryGeneral,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Encap-Session-Timeout",
			AttributeID:    23,
			Label:       "Wireless Encap Session Timeout",
			Description: "Encapsulation session timeout in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Mikrotik-Wireless-Encap-Type",
			AttributeID:    22,
			Label:       "Wireless Encap Type",
			Description: "Wireless encapsulation type",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "WPA"},
				{Value: "2", Label: "WPA2"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Mac-Format",
			AttributeID:    32,
			Label:       "Wireless MAC Format",
			Description: "Wireless MAC address format",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "Default"},
				{Value: "1", Label: "XX:XX:XX:XX:XX:XX"},
				{Value: "2", Label: "XX-XX-XX-XX-XX-XX"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Skip-802.1x",
			AttributeID:    5,
			Label:       "Wireless Skip 802.1x",
			Description: "Skip 802.1x authentication for this client",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Algo-Preauth",
			AttributeID:    34,
			Label:       "Wireless Algorithm Preauth",
			Description: "Enable algorithm preauthentication",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Protected-Frame",
			AttributeID:    26,
			Label:       "Wireless Protected Frame",
			Description: "Enable protected frames (802.11w)",
			DataType:    RadiusDataTypeBoolean,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
		},
		{
			Key:         "Mikrotik-Wireless-Sa-Query-Timeout",
			AttributeID:    27,
			Label:       "Wireless SA Query Timeout",
			Description: "SA Query timeout in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(100),
			Examples:    []string{"1", "2"},
		},
		{
			Key:         "Mikrotik-Wireless-Sa-Query-Retry",
			AttributeID:    28,
			Label:       "Wireless SA Query Retry",
			Description: "SA Query retry count",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinValue:    float64Ptr(0),
			MaxValue:    float64Ptr(10),
			Examples:    []string{"2", "4"},
		},
		{
			Key:         "Mikrotik-Advertise-URL",
			AttributeID:    12,
			Label:       "Advertise URL",
			Description: "URL to advertise to the client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			Pattern:     `^https?://[^\s]+$`,
			Examples:    []string{"https://example.com", "http://portal.example.com"},
		},
		{
			Key:         "Mikrotik-Advertise-Interval",
			AttributeID:    13,
			Label:       "Advertise Interval",
			Description: "Advertisement interval in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MinValue:    float64Ptr(0),
			Examples:    []string{"300", "600"},
		},
		{
			Key:         "Mikrotik-Delegated-IPv6-Pool",
			AttributeID:    41,
			Label:       "Delegated IPv6 Pool",
			Description: "IPv6 pool for prefix delegation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"ipv6-pool1", "pd-pool"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-Delegated-IPv6-Prefix",
			AttributeID:    40,
			Label:       "Delegated IPv6 Prefix",
			Description: "IPv6 prefix to delegate",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Pattern:     `^[0-9a-fA-F:]+/\d{1,3}$`,
			Examples:    []string{"2001:db8::/64", "fd00::/48"},
			CoAApplicable:  true,
		},
		{
			Key:         "Mikrotik-IPsec-Policy",
			AttributeID:    42,
			Label:       "IPsec Policy",
			Description: "IPsec policy for the user",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"policy1", "ipsec-policy"},
		},
		{
			Key:         "Mikrotik-IPsec-Secret",
			AttributeID:    43,
			Label:       "IPsec Secret",
			Description: "IPsec pre-shared key",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			Required:    false,
			MinLength:   intPtr(1),
			MaxLength:   intPtr(128),
		},
		{
			Key:         "Mikrotik-PPPoe-Service-Name",
			AttributeID:    44,
			Label:       "PPPoE Service Name",
			Description: "PPPoE service name",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Examples:    []string{"isp-service", "pppoe"},
		},
		{
			Key:         "Mikrotik-PPTP-Encoding",
			AttributeID:    45,
			Label:       "PPTP Encoding",
			Description: "PPTP encoding type",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "MPPE 40-bit"},
				{Value: "2", Label: "MPPE 128-bit"},
			},
		},
		{
			Key:         "Mikrotik-L2TP-Encoding",
			AttributeID:    46,
			Label:       "L2TP Encoding",
			Description: "L2TP encoding type",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryAuthorization,
			Required:    false,
			Options: []FieldOption{
				{Value: "0", Label: "None"},
				{Value: "1", Label: "MPPE 40-bit"},
				{Value: "2", Label: "MPPE 128-bit"},
			},
		},
		{
			Key:         "Mikrotik-Wireless-Comment",
			AttributeID:    47,
			Label:       "Wireless Comment",
			Description: "Comment for wireless client",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			Required:    false,
			MaxLength:   intPtr(255),
		},
	},
}
