package provider

// radiusVendorCambium holds the RADIUS attribute dictionary for CAMBIUM.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorCambium = VendorDictionaryInfo{
	Value:       "CAMBIUM",
	Label:       "Cambium Networks",
	Description: "Cambium Networks RADIUS VSA (Vendor ID: 17713). Used with Cambium PMP/PTP fixed wireless and cnMaestro-managed devices.",
	VendorID:    17713,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Cambium-Canopy-Timeout",
			AttributeID:    8,
			Label:       "Session Timeout",
			Description: "Maximum session duration for the subscriber module in seconds",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategorySession,
			MinValue:    float64Ptr(0),
			Examples:    []string{"3600", "86400"},
		},
		{
			Key:         "Cambium-Canopy-Vector",
			AttributeID:    7,
			Label:       "Canopy Vector",
			Description: "Internal Canopy vector identifier for subscriber classification",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryGeneral,
			MinValue:    float64Ptr(0),
		},
		{
			Key:         "Cambium-Gateway-Link-Speed",
			AttributeID:    9,
			Label:       "Gateway Link Speed",
			Description: "Aggregate link speed of the gateway uplink in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"100000", "1000000"},
		},
		{
			Key:         "Cambium-Subscriber-Group",
			AttributeID:    1,
			Label:       "Subscriber Group",
			Description: "Subscriber group name used for QoS and policy templating",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"residential", "business", "trial"},
		},
		{
			Key:         "Cambium-Subscriber-Frequency-Level",
			AttributeID:    2,
			Label:       "Subscriber Frequency Level",
			Description: "RF frequency level assignment tier for the subscriber",
			DataType:    RadiusDataTypeEnum,
			Category:    RadiusCategoryQoS,
			Options: []FieldOption{
				{Value: "0", Label: "Level 0 (Lowest)"},
				{Value: "1", Label: "Level 1"},
				{Value: "2", Label: "Level 2"},
				{Value: "3", Label: "Level 3"},
				{Value: "4", Label: "Level 4 (Highest)"},
			},
		},
		{
			Key:         "Cambium-Address-Filter",
			AttributeID:    11,
			Label:       "Address Filter",
			Description: "ACL / address-filter name to apply to the subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryFiltering,
			MaxLength:   intPtr(64),
			Examples:    []string{"block-p2p", "allow-all"},
		},
		{
			Key:         "Cambium-AP-DL-Bandwidth",
			AttributeID:    5,
			Label:       "AP Downlink Bandwidth",
			Description: "Maximum downlink (AP → SM) bandwidth allocation in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200", "102400"},
		},
		{
			Key:         "Cambium-AP-UL-Bandwidth",
			AttributeID:    6,
			Label:       "AP Uplink Bandwidth",
			Description: "Maximum uplink (SM → AP) bandwidth allocation in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"5120", "20480"},
		},
		{
			Key:         "Cambium-SM-DL-Bandwidth",
			AttributeID:    3,
			Label:       "SM Downlink Bandwidth",
			Description: "Per-SM maximum downlink bandwidth in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "51200"},
		},
		{
			Key:         "Cambium-SM-UL-Bandwidth",
			AttributeID:    4,
			Label:       "SM Uplink Bandwidth",
			Description: "Per-SM maximum uplink bandwidth in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"5120", "20480"},
		},
		{
			Key:         "Cambium-Current-Channel",
			AttributeID:    10,
			Label:       "Current Channel",
			Description: "RF channel number the subscriber module is currently using",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryMobility,
			MinValue:    float64Ptr(1),
		},
	},
}