package provider

// radiusVendorCalix holds the RADIUS attribute dictionary for CALIX.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorCalix = VendorDictionaryInfo{
	Value:       "CALIX",
	Label:       "Calix",
	Description: "Calix RADIUS VSA (Vendor ID: 10430). Used with Calix E-Series and AXOS OLT platforms. Widely deployed by US rural and community ISPs for fibre and DSL subscriber management.",
	VendorID:    10430,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "Calix-Service-Profile",
			AttributeID:    3,
			Label:       "Service Profile",
			Description: "Calix service profile name defining the subscriber's access tier",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"100Mbps-Residential", "1Gbps-Business"},
		},
		{
			Key:         "Calix-Rate-Limit-Up",
			AttributeID:    5,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream bandwidth for the subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "102400", "1024000"},
		},
		{
			Key:         "Calix-Rate-Limit-Down",
			AttributeID:    4,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream bandwidth for the subscriber in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"51200", "204800", "1024000"},
		},
		{
			Key:         "Calix-Primary-DNS",
			AttributeID:    6,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "Calix-Secondary-DNS",
			AttributeID:    7,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the subscriber",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "Calix-VLAN-ID",
			AttributeID:    1,
			Label:       "VLAN ID",
			Description: "S-VLAN or C-VLAN ID assigned to the subscriber's ONT port",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryTunneling,
			MinValue:    float64Ptr(1),
			MaxValue:    float64Ptr(4094),
			Examples:    []string{"100", "200"},
		},
		{
			Key:         "Calix-IP-Pool",
			AttributeID:    8,
			Label:       "IP Pool",
			Description: "Address pool name from which the subscriber IP is allocated",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"pool-fiber", "pool-dsl"},
		},
		{
			Key:         "Calix-Subscriber-ID",
			AttributeID:    2,
			Label:       "Subscriber ID",
			Description: "Unique subscriber identifier for OSS/BSS correlation",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthentication,
			MaxLength:   intPtr(64),
			Examples:    []string{"acct-0001234", "cust-98765"},
		},
		{
			Key:         "Calix-ONT-Port",
			AttributeID:    9,
			Label:       "ONT Port",
			Description: "Optical Network Terminal port identifier the subscriber is connected to",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryGeneral,
			MaxLength:   intPtr(32),
			Examples:    []string{"ont-1/1/1", "pon-0/0/1:1"},
		},
	},
}