package provider

// radiusVendorNetelastic holds the RADIUS attribute dictionary for NETELASTIC.
// It is registered into RadiusDictionaryRegistry in radius.attribute.registry.go.
var radiusVendorNetelastic = VendorDictionaryInfo{
	Value:       "NETELASTIC",
	Label:       "NetElastic vBNG/CGNAT",
	Description: "NetElastic software-based vBNG and CGNAT RADIUS VSA (Vendor ID: 9130). Used for subscriber session management and dynamic CGNAT policy control.",
	VendorID:    9130,
	Attributes: []RadiusAttributeSchema{
		{
			Key:         "NE-Subscriber-Profile",
			AttributeID:    7,
			Label:       "Subscriber Profile",
			Description: "Service profile name defining the subscriber's overall access policy",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"profile-100m", "profile-1g-business"},
		},
		{
			Key:         "NE-QoS-Profile",
			AttributeID:    8,
			Label:       "QoS Profile",
			Description: "QoS policy profile controlling shaping/policing for this subscriber",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryQoS,
			MaxLength:   intPtr(64),
			Examples:    []string{"qos-100m-down-10m-up", "qos-best-effort"},
		},
		{
			Key:         "NE-Rate-Limit-Up",
			AttributeID:    2,
			Label:       "Rate Limit Up",
			Description: "Maximum upstream (subscriber-to-network) rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"10240", "102400"},
		},
		{
			Key:         "NE-Rate-Limit-Down",
			AttributeID:    1,
			Label:       "Rate Limit Down",
			Description: "Maximum downstream (network-to-subscriber) rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"51200", "1024000"},
		},
		{
			Key:         "NE-Burst-Up",
			AttributeID:    4,
			Label:       "Burst Up",
			Description: "Upstream burst rate permitted above the committed rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"20480"},
		},
		{
			Key:         "NE-Burst-Down",
			AttributeID:    3,
			Label:       "Burst Down",
			Description: "Downstream burst rate permitted above the committed rate in kbps",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"102400"},
		},
		{
			Key:         "NE-IP-Pool",
			AttributeID:    5,
			Label:       "IP Pool",
			Description: "Private IP address pool name from which to allocate the subscriber's inside address",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"pool-residential", "pool-cgnat-private"},
		},
		{
			Key:         "NE-NAT-Policy",
			AttributeID:    10,
			Label:       "NAT Policy",
			Description: "CGNAT policy name controlling NAT44 translation rules, port allocation, and timeouts",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"nat-pol-default", "nat-pol-restricted"},
		},
		{
			Key:         "NE-NAT-Pool",
			AttributeID:    9,
			Label:       "NAT Pool",
			Description: "Public IP address pool from which CGNAT outside addresses are drawn",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"nat-outside-pool-1", "cgnat-pub-pool"},
		},
		{
			Key:         "NE-Session-ID",
			AttributeID:    14,
			Label:       "Session ID",
			Description: "Unique session identifier assigned by the vBNG for this subscriber session",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategorySession,
			MaxLength:   intPtr(64),
			Examples:    []string{"sess-0000000001"},
		},
		{
			Key:         "NE-Primary-Dns",
			AttributeID:    12,
			Label:       "Primary DNS",
			Description: "Primary DNS server pushed to the subscriber via PPP or DHCP",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.8.8", "1.1.1.1"},
		},
		{
			Key:         "NE-Secondary-Dns",
			AttributeID:    13,
			Label:       "Secondary DNS",
			Description: "Secondary DNS server pushed to the subscriber via PPP or DHCP",
			DataType:    RadiusDataTypeIP,
			Category:    RadiusCategoryAuthorization,
			Examples:    []string{"8.8.4.4", "1.0.0.1"},
		},
		{
			Key:         "NE-Max-Sessions",
			AttributeID:    15,
			Label:       "Max Sessions",
			Description: "Maximum concurrent NAT sessions allowed for this subscriber",
			DataType:    RadiusDataTypeInteger,
			Category:    RadiusCategoryQoS,
			MinValue:    float64Ptr(0),
			Examples:    []string{"1024", "4096", "0"},
		},
		{
			Key:         "NE-IPv6-Pool",
			AttributeID:    6,
			Label:       "IPv6 Pool",
			Description: "IPv6 prefix pool name for DHCPv6 or SLAAC assignment",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"ipv6-pool-pd-56", "ipv6-pool-slaac"},
		},
		{
			Key:         "NE-VRF-Name",
			AttributeID:    11,
			Label:       "VRF Name",
			Description: "VRF / routing context name the subscriber session is placed in",
			DataType:    RadiusDataTypeString,
			Category:    RadiusCategoryAuthorization,
			MaxLength:   intPtr(64),
			Examples:    []string{"vrf-residential", "vrf-business"},
		},
	},
}